### ISSUE TITLE
Service was dead after Deadline Exceed

### ISSUE THREAD

**Issue by ninxxxxx** [ecobee/nodejs-gcloud-pubsub-module#4]
i always got this problem and it made the service to be dead can't respond all the next things

**Comment by arvinsingla** [comment]
Hey @ninxxxxx are you able to provide some more details? Is this occurring when you're setting up the microservice for listening to subscriptions? Or is this happening when you're publishing to a topic?

**Comment by ninxxxxx** [comment]
<img width="1333" alt="Screen Shot 2562-10-11 at 10 33 59" src="https://user-images.githubusercontent.com/7845391/66622681-d34b3a80-ec12-11e9-80b2-71c00d86c077.png">

**Comment by arvinsingla** [comment]
Sorry for the long delay on this issue. It should now be resolved with the latest [v0.3.0](https://github.com/ecobee/nodejs-gcloud-pubsub-module/tree/v0.3.0) release.
